import {W,LEVELS,createState,startAttempt,advance,LIMIT_X,LIMIT_Y,cameraAt} from './physics.js';
import {readScores,saveScore,formatTime} from './leaderboard.js';
import {FlightRecorder,REPLAY_VERSION} from './flight-replay.js';
import {fetchOnlineScores,createFlightTicket,submitOnlineScore} from './online-leaderboard.js';
import {shipPose,drawBackground,drawTerrain,drawDust,drawPad,drawShip} from './visuals.js';
import {JetAudio} from './sound.js';
const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d');
$('browser-hint').hidden=true;
const art={};for(const [key,file]of Object.entries({sky:'sky',ship:'lander',terrain:'terrain'})){art[key]=new Image();art[key].src=`art/${file}.png`;}
// Texte der drei Missionen; Physik und Schwierigkeit stehen in physics.js (LEVELS).
const MISSIONS=[
 {place:'auf dem Mond',brief:'Folge der Mondoberfläche bis zur verborgenen Landezone. Weiche Meteoriten aus.',tip:'↑ hält dich oben · ← bremst den Flug nach rechts',hidden:'→ Die Landezone liegt hinter den Bergen'},
 {place:'auf dem Mars',brief:'Raue Zackenkämme, stärkere Schwerkraft und Staubböen, die dich seitlich versetzen. Mehr Meteoriten, schmalere Plattform.',tip:'Böen versetzen dich seitlich · früh gegensteuern',hidden:'→ Die Landezone liegt hinter den Kraterkämmen'},
 {place:'im Canyon von Xenara',brief:'Fremder Planet mit Felsnadeln. Die Landezone liegt tief in einem engen Canyon: über dem Tal abbremsen und kontrolliert senkrecht hinabsinken. Die Felswände sind tödlich.',tip:'Über der Plattform abbremsen · dann langsam in den Canyon sinken',hidden:'→ Die Landezone liegt tief im Canyon'}
];
let state=createState(),particles=[],last=performance.now(),accumulator=0,endedAt=0,muted=true;
const audio=new JetAudio();
let savedFlight=false,attitude=0,gearExtension=0,flightTicket=null,flightRecorder=null,preparing=false;
// Expedition: Landung → nächste Mission, Absturz → neuer Versuch derselben Mission. Die Zeit aller Versuche zählt.
let baseSeed=0,campaign={level:0,attempt:0,total:0,splits:[]},nextAction='expedition',expeditionDone=false;
function scoreStorage(){try{return localStorage;}catch{return null;}}
function renderScores(scores=readScores(scoreStorage()).scores){const body=$('score-rows');body.replaceChildren();for(const [i,s]of scores.entries()){const row=document.createElement('tr');for(const v of [String(i+1),s.name,formatTime(s.seconds)]){const cell=document.createElement('td');cell.textContent=v;row.append(cell);}body.append(row);}$('score-empty').hidden=scores.length>0;}
function showScoreMode(online,message=''){$('score-description').innerHTML=online?'Gemeinsames Online-Leaderboard · Expedition 3.0<br>Kürzeste Gesamtflugzeit über alle drei Missionen gewinnt. Fehlversuche zählen mit. Nur serverseitig geprüfte Flüge zählen.':'Lokales Ersatz-Leaderboard auf diesem Gerät · Expedition 3.0<br>Das Online-Leaderboard ist gerade nicht erreichbar.';$('score-note').textContent=online?'Öffentlich sichtbar sind nur Name/Kürzel und Gesamtzeit. Es ist keine Anmeldung nötig.':'Lokale Zeiten bleiben nur in diesem Browser und werden nicht als gemeinsame Wertung ausgegeben.';$('score-service-status').textContent=message;}
async function refreshScores(){try{const scores=await fetchOnlineScores(REPLAY_VERSION);renderScores(scores);showScoreMode(true);}catch(error){renderScores();showScoreMode(false,error.message);}}
renderScores();refreshScores();renderSteps(0,0);
$('refresh-scores').onclick=refreshScores;
$('score-form').onsubmit=async e=>{e.preventDefault();if(!expeditionDone||savedFlight)return;const seconds=campaign.total;$('save-score').disabled=true;$('score-feedback').textContent='Gesamtzeit wird geprüft …';try{if(flightTicket&&flightRecorder){const result=await submitOnlineScore(flightTicket,$('pilot-name').value,flightRecorder.snapshot());renderScores(result.scores);showScoreMode(true);$('score-feedback').textContent='Geprüft und im gemeinsamen Leaderboard gespeichert.';}else{renderScores(saveScore(scoreStorage(),$('pilot-name').value,seconds));showScoreMode(false,'Diese Expedition hatte kein Online-Ticket.');$('score-feedback').textContent='Nur lokal auf diesem Gerät gespeichert.';}savedFlight=true;}catch(error){try{renderScores(saveScore(scoreStorage(),$('pilot-name').value,seconds));showScoreMode(false,'Online-Speicherung fehlgeschlagen: '+error.message);$('score-feedback').textContent='Die Gesamtzeit wurde nur lokal auf diesem Gerät gespeichert.';savedFlight=true;}catch(localError){$('score-feedback').textContent=error.message+' '+localError.message;$('save-score').disabled=false;}}};
$('music').onclick=async()=>{const enabled=!audio.musicEnabled;$('music').disabled=true;const ok=await audio.setMusic(enabled);$('music').setAttribute('aria-pressed',String(Boolean(audio.musicEnabled)));$('music-label').textContent=ok?(audio.musicEnabled?'Musik an':'Musik aus'):'Musik nicht verfügbar';$('music').disabled=false;};
const keyboard=new Set(),touch=new Map(),keys=new Set();
function syncKeys(){keys.clear();for(const k of keyboard)keys.add(k);for(const k of touch.values())keys.add(k);document.querySelectorAll('[data-key]').forEach(b=>b.classList.toggle('active',keys.has(b.dataset.key)));audio.thrust(state.status==='running'&&!muted?keys.size:0);}
function clearKeys(){keyboard.clear();touch.clear();syncKeys();}
// Fortschrittsanzeige im Overlay: erledigt, aktuell, offen.
function renderSteps(current,doneUpTo){const list=$('mission-steps');list.replaceChildren();LEVELS.forEach((L,i)=>{const item=document.createElement('li');item.textContent=`${i+1} ${L.name}`;item.className=i<doneUpTo?'done':i===current?'current':'';if(i<doneUpTo)item.setAttribute('aria-label',`Mission ${i+1} ${L.name} erfüllt`);list.append(item);});list.hidden=false;}
function showOverlay(title,detail,button,{current=campaign.level,done=campaign.level,focus=true,brief=''}={}){$('message').innerHTML=title;$('detail').textContent=detail;$('brief').textContent=brief;$('brief').hidden=!brief;$('start').textContent=button;renderSteps(current,done);$('overlay').hidden=false;$('announcement').textContent=detail+(brief?' '+brief:'');if(focus)$('start').focus({preventScroll:true});}
function updateMission(){$('mission').textContent=`${state.level+1}/${LEVELS.length} · ${LEVELS[state.level].name.toUpperCase()}`;}
async function newExpedition(){if(preparing)return;clearKeys();preparing=true;
 // Laufenden Flug sofort beenden, auch wenn die Vorbereitung kurz auf das Netz wartet.
 audio.music(false);state=createState(0,0);particles=[];$('tip').hidden=true;$('pause').disabled=true;$('start').disabled=true;$('restart').disabled=true;$('start').textContent='Expedition wird vorbereitet …';
 try{const scores=await fetchOnlineScores(REPLAY_VERSION);renderScores(scores);const issued=await createFlightTicket();if(issued.version!==REPLAY_VERSION)throw new Error('Das Online-Leaderboard ist noch nicht auf diese Spielversion umgestellt.');flightTicket=issued.ticket;flightRecorder=new FlightRecorder();baseSeed=issued.seed;showScoreMode(true);}
 catch(error){flightTicket=null;flightRecorder=null;baseSeed=Math.floor(Math.random()*4294967296);renderScores();showScoreMode(false,error.message);}
 campaign={level:0,attempt:0,total:0,splits:[]};expeditionDone=false;savedFlight=false;$('score-form').hidden=true;$('save-score').disabled=false;$('score-feedback').textContent='';preparing=false;$('start').disabled=false;$('restart').disabled=false;launch();}
function launch(){state=startAttempt(baseSeed,campaign.level,campaign.attempt);particles=[];attitude=0;gearExtension=0;$('tip').textContent=MISSIONS[campaign.level].tip;$('tip').hidden=false;fly();}
function fly(){clearKeys();state.status='running';nextAction='expedition';$('overlay').hidden=true;endedAt=0;accumulator=0;last=performance.now();$('pause').disabled=false;$('pause-label').textContent='Pause';updateMission();audio.resume();audio.music(true);canvas.focus();}
function primaryAction(){if(nextAction==='resume')fly();else if(nextAction==='next'||nextAction==='retry')launch();else newExpedition();}
function reset(){newExpedition();}
function pause(){if(state.status==='running'){state.status='paused';nextAction='resume';audio.music(false);clearKeys();$('tip').hidden=true;$('pause-label').textContent='Weiter';showOverlay(`Mission ${state.level+1} pausiert.`,'Atme durch. Dein Flug wartet auf dich.','Weiterfliegen');}else if(state.status==='paused')fly();}
$('start').onclick=primaryAction;$('restart').onclick=reset;$('pause').onclick=pause;$('sound').onclick=async()=>{const button=$('sound');button.disabled=true;const enabled=await audio.setEnabled(muted);muted=!audio.enabled;button.setAttribute('aria-pressed',String(!muted));$('sound-label').textContent=enabled?(muted?'Sound aus':'Sound an'):'Sound nicht verfügbar';button.disabled=false;syncKeys();};
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(e.key.startsWith('Arrow')){e.preventDefault();if(state.status==='running'){keyboard.add(e.key);syncKeys();}}else if(!e.repeat){if(e.key==='Escape'||e.key.toLowerCase()==='p')pause();if(e.key.toLowerCase()==='r')reset();}});
window.addEventListener('keyup',e=>{keyboard.delete(e.key);syncKeys();});
window.addEventListener('blur',()=>{clearKeys();if(state.status==='running')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.status==='running')pause();});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();if(state.status==='running'){b.setPointerCapture(e.pointerId);touch.set(e.pointerId,b.dataset.key);syncKeys();}});const release=e=>{touch.delete(e.pointerId);syncKeys();};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);b.addEventListener('contextmenu',e=>e.preventDefault());}
function explode(){for(let i=0;i<95;i++){const a=Math.random()*Math.PI*2,v=35+Math.random()*180;particles.push({x:state.x,y:state.y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:1+Math.random(),color:i%3?'#ff9855':'#f8ebad'});}audio.result(false);}
function finish(){audio.music(false);clearKeys();endedAt=performance.now();$('tip').hidden=true;$('pause').disabled=true;campaign.total+=state.elapsed;const level=state.level,L=LEVELS[level];
 if(state.status==='crashed'){campaign.attempt++;nextAction='retry';explode();$('announcement').textContent=state.reason;return;}
 audio.result(true);campaign.splits.push(state.elapsed);
 if(level<LEVELS.length-1){campaign.level++;campaign.attempt=0;nextAction='next';const next=campaign.level;showOverlay(`Mission ${level+1} erfüllt!<span class="sub">Sanft gelandet ${MISSIONS[level].place}.</span>`,`Missionszeit ${formatTime(state.elapsed)} · Gesamtzeit ${formatTime(campaign.total)}`,`Weiter zu Mission ${next+1} · ${LEVELS[next].name}`,{current:next,done:next,brief:`Nächstes Ziel ${LEVELS[next].name}: ${MISSIONS[next].brief} ${LEVELS[next].time} Sekunden.`});return;}
 expeditionDone=true;nextAction='expedition';showOverlay('Expedition erfüllt!<span class="sub">Alle drei Landungen geschafft.</span>',`Gesamtzeit ${formatTime(campaign.total)}${campaign.total>campaign.splits.reduce((a,b)=>a+b,0)+.005?' inklusive Fehlversuche':''}`,'Neue Expedition starten',{current:-1,done:LEVELS.length,focus:false,brief:`${campaign.splits.map((t,i)=>LEVELS[i].name+' '+formatTime(t)).join(' · ')}. Trag dich unten ins Leaderboard ein.`});$('score-form').hidden=false;$('pilot-name').focus({preventScroll:true});$('announcement').textContent=`Expedition erfüllt. Gesamtzeit ${formatTime(campaign.total)}.`;}
function flame(x,y,dx,dy){ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(dy,dx));const len=15+Math.random()*12;ctx.fillStyle='#ff9443';ctx.beginPath();ctx.moveTo(0,-4);ctx.lineTo(len,0);ctx.lineTo(0,4);ctx.fill();ctx.fillStyle='#ffeab1';ctx.beginPath();ctx.moveTo(0,-2);ctx.lineTo(len*.55,0);ctx.lineTo(0,2);ctx.fill();ctx.restore();}
// Missionstitel blendet zu Beginn jedes Versuchs kurz im Spielfeld ein.
function banner(){if(state.status!=='running'||state.elapsed>3.2)return;const alpha=Math.min(1,(3.2-state.elapsed)/.8,state.elapsed/.3+.2);ctx.save();ctx.globalAlpha=alpha;ctx.textAlign='center';ctx.fillStyle='#08141ce0';ctx.fillRect(W/2-230,74,460,82);ctx.strokeStyle='#b4e74566';ctx.strokeRect(W/2-230,74,460,82);ctx.fillStyle='#b4e745';ctx.font='600 14px Mono,monospace';ctx.fillText(`MISSION ${state.level+1} / ${LEVELS.length}${campaign.attempt?` · VERSUCH ${campaign.attempt+1}`:''}`,W/2,100);ctx.fillStyle='#f8f1e5';ctx.font='800 34px Inter,Arial,sans-serif';ctx.fillText(LEVELS[state.level].name.toUpperCase(),W/2,140);ctx.restore();}
function draw(dt){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,level=state.level,L=LEVELS[level],pad=L.pad,camera=cameraAt(state.x,L);drawBackground(ctx,art.sky,camera,state.elapsed,reduced,level,state.wind||0);
ctx.save();ctx.translate(-camera,0);
drawTerrain(ctx,art.terrain,level,camera,state.elapsed,reduced);
drawPad(ctx,level);
for(const m of state.meteors){ctx.save();ctx.translate(m.x,m.y);const tailX=-m.vx*.9,tailY=-m.vy*.9;const tail=ctx.createLinearGradient(0,0,tailX,tailY);tail.addColorStop(0,'#ffb16eaa');tail.addColorStop(1,'#ffb16e00');ctx.fillStyle=tail;ctx.beginPath();ctx.moveTo(-m.r,0);ctx.lineTo(tailX,tailY);ctx.lineTo(m.r,0);ctx.fill();ctx.rotate(m.angle);ctx.fillStyle='#ad9382';ctx.strokeStyle='#f9c58a';ctx.beginPath();for(let i=0;i<7;i++){const a=i/7*Math.PI*2,r=m.r*(i%2?.8:1);i?ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r):ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
if(state.status!=='crashed'){if(state.status==='running'){if(keys.has('ArrowUp'))flame(state.x,state.y+15,0,1);if(keys.has('ArrowDown'))flame(state.x,state.y-14,0,-1);if(keys.has('ArrowRight'))flame(state.x-12,state.y,-1,0);if(keys.has('ArrowLeft'))flame(state.x+12,state.y,1,0);}const pose=shipPose(state,keys);if(state.status!=='paused'){attitude+=(pose.angle-attitude)*(1-Math.exp(-dt*5));gearExtension+=(pose.gear-gearExtension)*(1-Math.exp(-dt*7));}drawShip(ctx,state.x,state.y,attitude,gearExtension);}
for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=30*dt;ctx.globalAlpha=Math.max(0,Math.min(1,p.life));ctx.fillStyle=p.color;if(!reduced)ctx.fillRect(p.x,p.y,3,3);}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);ctx.restore();
drawDust(ctx,level,camera,state.elapsed,reduced,state.wind||0);banner();
if(state.status==='crashed'&&endedAt&&performance.now()-endedAt>650&&$('overlay').hidden)showOverlay(`Mission ${level+1} gescheitert.`,state.reason,`Mission ${level+1} erneut versuchen`,{brief:`Die Flugzeit zählt weiter zur Gesamtzeit (${formatTime(campaign.total)}). Neustart beginnt die Expedition von vorn.`});
const remaining=Math.ceil(state.time);$('time').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');
$('total-time').textContent=formatTime(campaign.total+(state.status==='running'||state.status==='paused'?state.elapsed:0));
const windText=L.wind?(Math.abs(state.wind||0)<.4?'ruhig':((state.wind>0?'→ ':'← ')+(Math.abs(state.wind)/8).toFixed(1).replace('.',',')+' m/s²')):'';$('wind').hidden=!L.wind;$('wind-value').textContent=windText;
$('distance').textContent=Math.min(100,Math.floor(Math.max(0,state.x-L.start.x)/(pad.left-L.start.x)*100))+' %';const warning=state.status==='running'&&state.x<pad.left-900&&state.nextStorm-state.elapsed<2;$('meteor-warning').hidden=!warning;
const center=(pad.left+pad.right)/2,meters=Math.max(0,Math.round((center-state.x)/8));const brakingDistance=state.vx>0?state.vx*state.vx/96:0;const inApproach=state.x>pad.left-1200||center-state.x<brakingDistance+650;const above=Math.abs(center-state.x)<(pad.right-pad.left)/2-10&&Math.abs(state.vx)<=LIMIT_X;
$('landing-guide').textContent=state.status==='landed'?'✓ Sicher gelandet':!inApproach?MISSIONS[level].hidden:above?'↓ Landezone unter dir · langsam sinken':state.x>center?'← Landezone hinter dir · Gegenschub':(Math.abs(state.vx)>LIMIT_X&&meters*8<brakingDistance+350?'← Jetzt bremsen · ':'→ Landezone in ')+meters+' m';$('landing-guide').classList.toggle('brake',inApproach&&Math.abs(state.vx)>LIMIT_X);
$('time').classList.toggle('danger',state.time<15);$('vx').textContent=(state.vx/8).toFixed(1)+' m/s';$('vy').textContent=(state.vy/8).toFixed(1)+' m/s';$('vx').classList.toggle('danger',Math.abs(state.vx)>LIMIT_X);$('vy').classList.toggle('danger',Math.abs(state.vy)>LIMIT_Y);if(state.status==='running'&&state.elapsed>7)$('tip').hidden=true;
}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state.status==='running'){accumulator+=dt;while(accumulator>=1/120&&state.status==='running'){if(flightRecorder){try{flightRecorder.record(keys);}catch{flightRecorder=null;flightTicket=null;}}advance(state,keys,1/120);accumulator-=1/120;if(state.status!=='running')finish();}}draw(dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);
